"use client";

import { createContext, useContext, useState, ReactNode } from "react";
import { MarketStatus } from "@/types/type";
// Define ActiveTab type
type MarketDataType = {
  "_id": string,
  "marketField": number,
  "apiType": number,
  "task": string,
  "creator": string,
  "tokenA": string,
  "tokenB": string,
  "market": string,
  "question": string,
  "feedName": string,
  "value": number,
  "tradingAmountA": number,
  "tradingAmountB": number,
  "tokenAPrice": number,
  "tokenBPrice": number,
  "initAmount": number,
  "range": number,
  "date": string,
  "marketStatus": string,
  "imageUrl": string,
  "createdAt": string,
  "__v": number,
  "playerACount": number,
  "playerBCount": number,
  "totalInvestment": number,
  "description": string,
  "comments": number
}

// Define Global Context Type
interface GlobalContextType {
  activeTab: MarketStatus;
  markets: MarketDataType[];
  setActiveTab: (tab: MarketStatus) => void;
  formatMarketData: (data: MarketDataType[]) => void;
}

// Create Context
const GlobalContext = createContext<GlobalContextType | undefined>(undefined);

// Create Global Provider
export const GlobalProvider = ({ children }: { children: ReactNode }) => {
  const [activeTab, setActiveTab] = useState<MarketStatus>("ACTIVE");
  const [markets, setMarkets] = useState<MarketDataType[]>([
    // Sample Active Markets
    {
      _id: "1",
      marketField: 0,
      apiType: 0,
      task: "price",
      creator: "sample_creator_1",
      tokenA: "tokenA_1",
      tokenB: "tokenB_1",
      market: "market_1",
      question: "Will Bitcoin reach $100,000 by December 2024?",
      feedName: "BTC",
      value: 100000,
      tradingAmountA: 5000,
      tradingAmountB: 5000,
      tokenAPrice: 1000000000000,
      tokenBPrice: 1000000000000,
      initAmount: 10000,
      range: 0,
      date: "2025-05-13T12:00:00.000Z",
      marketStatus: "ACTIVE",
      imageUrl: "https://assets.coingecko.com/coins/images/1/large/bitcoin.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 80,
      playerBCount: 20,
      totalInvestment: 10,
      description: "This market will resolve to Yes if Bitcoin reaches $100,000 by December 31, 2024",
      comments: 0
    },
    {
      _id: "2",
      marketField: 0,
      apiType: 0,
      task: "price",
      creator: "sample_creator_2",
      tokenA: "tokenA_2",
      tokenB: "tokenB_2",
      market: "market_2",
      question: "Will Ethereum reach $5,000 by Q3 2024?",
      feedName: "ETH",
      value: 5000,
      tradingAmountA: 3000,
      tradingAmountB: 3000,
      tokenAPrice: 500000000000,
      tokenBPrice: 500000000000,
      initAmount: 6000,
      range: 0,
      date: "2025-05-16T12:00:00.000Z",
      marketStatus: "ACTIVE",
      imageUrl: "https://assets.coingecko.com/coins/images/279/large/ethereum.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 30,
      playerBCount: 70,
      totalInvestment: 15,
      description: "This market will resolve to Yes if Ethereum reaches $5,000 by September 30, 2024",
      comments: 0
    },
    {
      _id: "3",
      marketField: 1,
      apiType: 0,
      task: "sports",
      creator: "sample_creator_3",
      tokenA: "tokenA_3",
      tokenB: "tokenB_3",
      market: "market_3",
      question: "Will the Lakers win their next game?",
      feedName: "NBA",
      value: 0,
      tradingAmountA: 2000,
      tradingAmountB: 2000,
      tokenAPrice: 200000000000,
      tokenBPrice: 200000000000,
      initAmount: 4000,
      range: 0,
      date: "2025-05-15T12:00:00.000Z",
      marketStatus: "ACTIVE",
      imageUrl: "https://a.espncdn.com/i/teamlogos/nba/500/lal.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 55,
      playerBCount: 45,
      totalInvestment: 28,
      description: "This market will resolve to Yes if the Lakers win their next game",
      comments: 0
    },
    {
      _id: "4",
      marketField: 1,
      apiType: 0,
      task: "sports",
      creator: "sample_creator_4",
      tokenA: "tokenA_4",
      tokenB: "tokenB_4",
      market: "market_4",
      question: "Will Manchester United score at least 2 goals in their next match?",
      feedName: "Premier League",
      value: 2,
      tradingAmountA: 1500,
      tradingAmountB: 1500,
      tokenAPrice: 150000000000,
      tokenBPrice: 150000000000,
      initAmount: 3000,
      range: 0,
      date: "2025-05-14T12:00:00.000Z",
      marketStatus: "ACTIVE",
      imageUrl: "https://resources.premierleague.com/premierleague/badges/70/t1.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 10,
      playerBCount: 90,
      totalInvestment: 25,
      description: "This market will resolve to Yes if Manchester United scores 2 or more goals in their next match",
      comments: 0
    },
    // Sample Pending Markets
    {
      _id: "5",
      marketField: 0,
      apiType: 0,
      task: "price",
      creator: "sample_creator_5",
      tokenA: "tokenA_5",
      tokenB: "tokenB_5",
      market: "market_5",
      question: "Will Solana reach $200 by Q4 2024?",
      feedName: "SOL",
      value: 200,
      tradingAmountA: 0,
      tradingAmountB: 0,
      tokenAPrice: 0,
      tokenBPrice: 0,
      initAmount: 5000,
      range: 0,
      date: "2024-12-31",
      marketStatus: "PENDING",
      imageUrl: "https://assets.coingecko.com/coins/images/4128/large/solana.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 0,
      playerBCount: 0,
      totalInvestment: 9,
      description: "This market will resolve to Yes if Solana reaches $200 by December 31, 2024",
      comments: 0
    },
    {
      _id: "6",
      marketField: 0,
      apiType: 0,
      task: "price",
      creator: "sample_creator_6",
      tokenA: "tokenA_6",
      tokenB: "tokenB_6",
      market: "market_6",
      question: "Will Cardano reach $2 by 2025?",
      feedName: "ADA",
      value: 2,
      tradingAmountA: 0,
      tradingAmountB: 0,
      tokenAPrice: 0,
      tokenBPrice: 0,
      initAmount: 4000,
      range: 0,
      date: "2025-01-01",
      marketStatus: "PENDING",
      imageUrl: "https://assets.coingecko.com/coins/images/975/large/cardano.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 0,
      playerBCount: 0,
      totalInvestment: 3,
      description: "This market will resolve to Yes if Cardano reaches $2 by January 1, 2025",
      comments: 0
    },
    {
      _id: "7",
      marketField: 1,
      apiType: 0,
      task: "sports",
      creator: "sample_creator_7",
      tokenA: "tokenA_7",
      tokenB: "tokenB_7",
      market: "market_7",
      question: "Will the Warriors score at least 120 points in their next game?",
      feedName: "NBA",
      value: 120,
      tradingAmountA: 0,
      tradingAmountB: 0,
      tokenAPrice: 0,
      tokenBPrice: 0,
      initAmount: 3000,
      range: 0,
      date: "2024-04-25",
      marketStatus: "PENDING",
      imageUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/0/01/Golden_State_Warriors_logo.svg/1200px-Golden_State_Warriors_logo.svg.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 0,
      playerBCount: 0,
      totalInvestment: 0,
      description: "This market will resolve to Yes if the Warriors score 120 or more points in their next game",
      comments: 0
    },
    {
      _id: "8",
      marketField: 1,
      apiType: 0,
      task: "sports",
      creator: "sample_creator_8",
      tokenA: "tokenA_8",
      tokenB: "tokenB_8",
      market: "market_8",
      question: "Will Liverpool win their next Premier League match?",
      feedName: "Premier League",
      value: 0,
      tradingAmountA: 0,
      tradingAmountB: 0,
      tokenAPrice: 0,
      tokenBPrice: 0,
      initAmount: 3500,
      range: 0,
      date: "2024-04-30",
      marketStatus: "PENDING",
      imageUrl: "https://resources.premierleague.com/premierleague/badges/70/t14.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 0,
      playerBCount: 0,
      totalInvestment: 0,
      description: "This market will resolve to Yes if Liverpool wins their next Premier League match",
      comments: 0
    },
    // Additional ACTIVE sample markets
    {
      _id: "9",
      marketField: 0,
      apiType: 0,
      task: "price",
      creator: "sample_creator_9",
      tokenA: "tokenA_9",
      tokenB: "tokenB_9",
      market: "market_9",
      question: "Will Dogecoin reach $1 by 2025?",
      feedName: "DOGE",
      value: 1,
      tradingAmountA: 1200,
      tradingAmountB: 800,
      tokenAPrice: 1000000000,
      tokenBPrice: 1000000000,
      initAmount: 2000,
      range: 0,
      date: "2025-06-01T12:00:00.000Z",
      marketStatus: "ACTIVE",
      imageUrl: "https://assets.coingecko.com/coins/images/5/large/dogecoin.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 60,
      playerBCount: 40,
      totalInvestment: 8,
      description: "This market will resolve to Yes if Dogecoin reaches $1 by January 1, 2025",
      comments: 0
    },
    {
      _id: "10",
      marketField: 1,
      apiType: 0,
      task: "sports",
      creator: "sample_creator_10",
      tokenA: "tokenA_10",
      tokenB: "tokenB_10",
      market: "market_10",
      question: "Will the New York Yankees win their next game?",
      feedName: "MLB",
      value: 0,
      tradingAmountA: 1800,
      tradingAmountB: 2200,
      tokenAPrice: 2000000000,
      tokenBPrice: 2000000000,
      initAmount: 4000,
      range: 0,
      date: "2025-05-20T12:00:00.000Z",
      marketStatus: "ACTIVE",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/25/NewYorkYankees_PrimaryLogo.svg.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 45,
      playerBCount: 55,
      totalInvestment: 12,
      description: "This market will resolve to Yes if the Yankees win their next game",
      comments: 0
    },
    {
      _id: "11",
      marketField: 0,
      apiType: 0,
      task: "price",
      creator: "sample_creator_11",
      tokenA: "tokenA_11",
      tokenB: "tokenB_11",
      market: "market_11",
      question: "Will XRP surpass $2 by the end of 2024?",
      feedName: "XRP",
      value: 2,
      tradingAmountA: 2500,
      tradingAmountB: 2500,
      tokenAPrice: 2000000000,
      tokenBPrice: 2000000000,
      initAmount: 5000,
      range: 0,
      date: "2024-12-31T12:00:00.000Z",
      marketStatus: "ACTIVE",
      imageUrl: "https://assets.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 50,
      playerBCount: 50,
      totalInvestment: 20,
      description: "This market will resolve to Yes if XRP surpasses $2 by December 31, 2024",
      comments: 0
    },
    {
      _id: "12",
      marketField: 1,
      apiType: 0,
      task: "sports",
      creator: "sample_creator_12",
      tokenA: "tokenA_12",
      tokenB: "tokenB_12",
      market: "market_12",
      question: "Will the Dallas Cowboys win the next Super Bowl?",
      feedName: "NFL",
      value: 0,
      tradingAmountA: 3000,
      tradingAmountB: 2000,
      tokenAPrice: 2500000000,
      tokenBPrice: 2500000000,
      initAmount: 5000,
      range: 0,
      date: "2025-02-10T12:00:00.000Z",
      marketStatus: "ACTIVE",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/1/15/Dallas_Cowboys.svg.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 70,
      playerBCount: 30,
      totalInvestment: 18,
      description: "This market will resolve to Yes if the Dallas Cowboys win the next Super Bowl",
      comments: 0
    },
    {
      _id: "13",
      marketField: 0,
      apiType: 0,
      task: "price",
      creator: "sample_creator_13",
      tokenA: "tokenA_13",
      tokenB: "tokenB_13",
      market: "market_13",
      question: "Will Polkadot reach $50 by 2025?",
      feedName: "DOT",
      value: 50,
      tradingAmountA: 1000,
      tradingAmountB: 1000,
      tokenAPrice: 1000000000,
      tokenBPrice: 1000000000,
      initAmount: 2000,
      range: 0,
      date: "2025-06-30T12:00:00.000Z",
      marketStatus: "ACTIVE",
      imageUrl: "https://assets.coingecko.com/coins/images/12171/large/polkadot.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 40,
      playerBCount: 60,
      totalInvestment: 7,
      description: "This market will resolve to Yes if Polkadot reaches $50 by June 30, 2025",
      comments: 0
    },
    {
      _id: "14",
      marketField: 1,
      apiType: 0,
      task: "sports",
      creator: "sample_creator_14",
      tokenA: "tokenA_14",
      tokenB: "tokenB_14",
      market: "market_14",
      question: "Will Novak Djokovic win the next Grand Slam?",
      feedName: "Tennis",
      value: 0,
      tradingAmountA: 900,
      tradingAmountB: 1100,
      tokenAPrice: 1000000000,
      tokenBPrice: 1000000000,
      initAmount: 2000,
      range: 0,
      date: "2025-07-15T12:00:00.000Z",
      marketStatus: "ACTIVE",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/2/28/Novak_Djokovic_Australian_Open_2023_%28cropped%29.jpg",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 48,
      playerBCount: 52,
      totalInvestment: 6,
      description: "This market will resolve to Yes if Novak Djokovic wins the next Grand Slam",
      comments: 0
    },
    {
      _id: "15",
      marketField: 0,
      apiType: 0,
      task: "price",
      creator: "sample_creator_15",
      tokenA: "tokenA_15",
      tokenB: "tokenB_15",
      market: "market_15",
      question: "Will Chainlink reach $100 by 2025?",
      feedName: "LINK",
      value: 100,
      tradingAmountA: 800,
      tradingAmountB: 1200,
      tokenAPrice: 1000000000,
      tokenBPrice: 1000000000,
      initAmount: 2000,
      range: 0,
      date: "2025-12-31T12:00:00.000Z",
      marketStatus: "ACTIVE",
      imageUrl: "https://assets.coingecko.com/coins/images/877/large/chainlink-new-logo.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 38,
      playerBCount: 62,
      totalInvestment: 5,
      description: "This market will resolve to Yes if Chainlink reaches $100 by December 31, 2025",
      comments: 0
    },
    {
      _id: "16",
      marketField: 1,
      apiType: 0,
      task: "sports",
      creator: "sample_creator_16",
      tokenA: "tokenA_16",
      tokenB: "tokenB_16",
      market: "market_16",
      question: "Will the Boston Celtics win the NBA Finals?",
      feedName: "NBA",
      value: 0,
      tradingAmountA: 2100,
      tradingAmountB: 1900,
      tokenAPrice: 2000000000,
      tokenBPrice: 2000000000,
      initAmount: 4000,
      range: 0,
      date: "2025-06-20T12:00:00.000Z",
      marketStatus: "ACTIVE",
      imageUrl: "https://a.espncdn.com/i/teamlogos/nba/500/bos.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 53,
      playerBCount: 47,
      totalInvestment: 13,
      description: "This market will resolve to Yes if the Boston Celtics win the NBA Finals",
      comments: 0
    },
    // Additional PENDING sample markets
    {
      _id: "17",
      marketField: 0,
      apiType: 0,
      task: "price",
      creator: "sample_creator_17",
      tokenA: "tokenA_17",
      tokenB: "tokenB_17",
      market: "market_17",
      question: "Will Avalanche reach $100 by 2025?",
      feedName: "AVAX",
      value: 100,
      tradingAmountA: 0,
      tradingAmountB: 0,
      tokenAPrice: 0,
      tokenBPrice: 0,
      initAmount: 3000,
      range: 0,
      date: "2025-12-31",
      marketStatus: "PENDING",
      imageUrl: "https://assets.coingecko.com/coins/images/12559/large/coin-round-red.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 0,
      playerBCount: 0,
      totalInvestment: 0,
      description: "This market will resolve to Yes if Avalanche reaches $100 by December 31, 2025",
      comments: 0
    },
    {
      _id: "18",
      marketField: 1,
      apiType: 0,
      task: "sports",
      creator: "sample_creator_18",
      tokenA: "tokenA_18",
      tokenB: "tokenB_18",
      market: "market_18",
      question: "Will the Green Bay Packers win their next NFL game?",
      feedName: "NFL",
      value: 0,
      tradingAmountA: 0,
      tradingAmountB: 0,
      tokenAPrice: 0,
      tokenBPrice: 0,
      initAmount: 3500,
      range: 0,
      date: "2024-09-10",
      marketStatus: "PENDING",
      imageUrl: "https://upload.wikimedia.org/wikipedia/commons/5/50/Green_Bay_Packers_logo.svg.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 0,
      playerBCount: 0,
      totalInvestment: 0,
      description: "This market will resolve to Yes if the Packers win their next NFL game",
      comments: 0
    },
    {
      _id: "19",
      marketField: 0,
      apiType: 0,
      task: "price",
      creator: "sample_creator_19",
      tokenA: "tokenA_19",
      tokenB: "tokenB_19",
      market: "market_19",
      question: "Will Uniswap reach $20 by 2025?",
      feedName: "UNI",
      value: 20,
      tradingAmountA: 0,
      tradingAmountB: 0,
      tokenAPrice: 0,
      tokenBPrice: 0,
      initAmount: 2500,
      range: 0,
      date: "2025-12-31",
      marketStatus: "PENDING",
      imageUrl: "https://assets.coingecko.com/coins/images/12504/large/uniswap-uni.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 0,
      playerBCount: 0,
      totalInvestment: 0,
      description: "This market will resolve to Yes if Uniswap reaches $20 by December 31, 2025",
      comments: 0
    },
    {
      _id: "20",
      marketField: 1,
      apiType: 0,
      task: "sports",
      creator: "sample_creator_20",
      tokenA: "tokenA_20",
      tokenB: "tokenB_20",
      market: "market_20",
      question: "Will the Los Angeles Rams win their next NFL game?",
      feedName: "NFL",
      value: 0,
      tradingAmountA: 0,
      tradingAmountB: 0,
      tokenAPrice: 0,
      tokenBPrice: 0,
      initAmount: 3200,
      range: 0,
      date: "2024-09-15",
      marketStatus: "PENDING",
      imageUrl: "https://upload.wikimedia.org/wikipedia/en/8/8a/Los_Angeles_Rams_logo.svg.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 0,
      playerBCount: 0,
      totalInvestment: 0,
      description: "This market will resolve to Yes if the Rams win their next NFL game",
      comments: 0
    },
    {
      _id: "21",
      marketField: 0,
      apiType: 0,
      task: "price",
      creator: "sample_creator_21",
      tokenA: "tokenA_21",
      tokenB: "tokenB_21",
      market: "market_21",
      question: "Will Litecoin reach $500 by 2025?",
      feedName: "LTC",
      value: 500,
      tradingAmountA: 0,
      tradingAmountB: 0,
      tokenAPrice: 0,
      tokenBPrice: 0,
      initAmount: 2000,
      range: 0,
      date: "2025-12-31",
      marketStatus: "PENDING",
      imageUrl: "https://assets.coingecko.com/coins/images/2/large/litecoin.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 0,
      playerBCount: 0,
      totalInvestment: 0,
      description: "This market will resolve to Yes if Litecoin reaches $500 by December 31, 2025",
      comments: 0
    },
    {
      _id: "22",
      marketField: 1,
      apiType: 0,
      task: "sports",
      creator: "sample_creator_22",
      tokenA: "tokenA_22",
      tokenB: "tokenB_22",
      market: "market_22",
      question: "Will the Chicago Bulls win their next NBA game?",
      feedName: "NBA",
      value: 0,
      tradingAmountA: 0,
      tradingAmountB: 0,
      tokenAPrice: 0,
      tokenBPrice: 0,
      initAmount: 3100,
      range: 0,
      date: "2024-10-20",
      marketStatus: "PENDING",
      imageUrl: "https://a.espncdn.com/i/teamlogos/nba/500/chi.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 0,
      playerBCount: 0,
      totalInvestment: 0,
      description: "This market will resolve to Yes if the Bulls win their next NBA game",
      comments: 0
    },
    {
      _id: "23",
      marketField: 0,
      apiType: 0,
      task: "price",
      creator: "sample_creator_23",
      tokenA: "tokenA_23",
      tokenB: "tokenB_23",
      market: "market_23",
      question: "Will Cosmos reach $50 by 2025?",
      feedName: "ATOM",
      value: 50,
      tradingAmountA: 0,
      tradingAmountB: 0,
      tokenAPrice: 0,
      tokenBPrice: 0,
      initAmount: 2100,
      range: 0,
      date: "2025-12-31",
      marketStatus: "PENDING",
      imageUrl: "https://assets.coingecko.com/coins/images/1481/large/cosmos_hub.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 0,
      playerBCount: 0,
      totalInvestment: 0,
      description: "This market will resolve to Yes if Cosmos reaches $50 by December 31, 2025",
      comments: 0
    },
    {
      _id: "24",
      marketField: 1,
      apiType: 0,
      task: "sports",
      creator: "sample_creator_24",
      tokenA: "tokenA_24",
      tokenB: "tokenB_24",
      market: "market_24",
      question: "Will the Miami Heat win their next NBA game?",
      feedName: "NBA",
      value: 0,
      tradingAmountA: 0,
      tradingAmountB: 0,
      tokenAPrice: 0,
      tokenBPrice: 0,
      initAmount: 3300,
      range: 0,
      date: "2024-10-22",
      marketStatus: "PENDING",
      imageUrl: "https://a.espncdn.com/i/teamlogos/nba/500/mia.png",
      createdAt: new Date().toISOString(),
      __v: 0,
      playerACount: 0,
      playerBCount: 0,
      totalInvestment: 0,
      description: "This market will resolve to Yes if the Miami Heat win their next NBA game",
      comments: 0
    }
  ]);

  const formatMarketData = (data: MarketDataType[]) => {
    setMarkets(data);
  }

  return (
    <GlobalContext.Provider value={{ activeTab, markets, setActiveTab, formatMarketData }}>
      {children}
    </GlobalContext.Provider>
  );
};

// Custom Hook to use Global Context
export const useGlobalContext = () => {
  const context = useContext(GlobalContext);
  if (!context) {
    throw new Error("useGlobalContext must be used within a GlobalProvider");
  }
  return context;
};
