import { IconName } from "@/components/elements/Icons/Icons";
import type { Metadata } from "next";

export const marketCarouselItems = [
  {
    category: "Cryptocurrency",
    title: "Will Bitcoin hit 120k by the end of the month?",
    bgImage: "/carousel_11.png",
    mainImage: "/carousel_12.png",
    overlayImage: "/carousel_13.png",
  },
  {
    category: "Sports Betting",
    title: "Which NFL team will win the Super Bowl in 2025?",
    bgImage: "/carousel_21.png",
    mainImage: "/carousel_22.png",
    overlayImage: "/carousel_23.png",
  },
  {
    category: "Sports Betting",
    title: "Which NFL team will win the Super Bowl in 2025?",
    bgImage: "/carousel_21.png",
    mainImage: "/carousel_22.png",
    overlayImage: "/carousel_23.png",
  },
];

export const categories = [
  { name: "Trending", active: true, icon: "Trending" as IconName, color: "#07b3ff" },
  { name: "Sports Prediction Market", active: false, icon: "Sports" as IconName, color: "#838587" },
  { name: "Crypto", active: false, icon: "Crypto" as IconName, color: "#838587" },
  { name: "News", active: false, icon: "News" as IconName, color: "#838587" },
];

export const metadata: Metadata = {
  title: "Speculape",
  description: "Generated by create next app",
};

export const ranges = [
  "Small",
  "Exact",
  "Near",
  "Bigger"
]

export const marketField = [
  {
    name: "Coin Prediction Market",
    content: [
      {
        api_name: "Coingecho",
        needed_data: [
          {
            name: "vs_currency",
            placeholder: "usd"
          },
          {
            name: "id",
            placeholder: "solana"
          }
        ],
        task: null,
        api_link: (...args: string[]) => `https://api.coingecko.com/api/v3/simple/price?ids=${args[1]}&vs_currencies=${args[0]}`,
        market_keyword: (...args: string[]) => `id: ${args[1]}, vs_currency: ${args[0]}`,
      },
      {
        api_name: "Dexscreener",
        needed_data: [
          {
            name: "token",
            placeholder: "EGfWrQjqEexyPcZNUFGU8LypCikg34q2vqtk7hwBzWdS"
          }
        ],
        task: "$.pairs[0].priceUsd",
        api_link: (...args: string[]) => `https://api.dexscreener.com/latest/dex/tokens/${args[0]}`,
        market_keyword: (...args: string[]) => `token: ${args[0]}`,
      }
    ]
  },
  {
    name: "Sports Prediction Market",
    content: [
      {
        api_name: "NBA",
        needed_data: [
          {
            name: "sport",
            placeholder: "basketball"
          },
          {
            name: "league",
            placeholder: "NBA"
          },
          {
            name: "team",
            placeholder: "Lakers"
          },
          {
            name: "stat_type",
            placeholder: "points"
          }
        ],
        task: null,
        api_link: (...args: string[]) => `https://api.sportsdata.io/v3/nba/stats/json/PlayerGameStatsByDate/${args[0]}/${args[1]}`,
        market_keyword: (...args: string[]) => `sport: ${args[0]}, league: ${args[1]}, team: ${args[2]}, stat: ${args[3]}`,
      },
      {
        api_name: "NFL",
        needed_data: [
          {
            name: "sport",
            placeholder: "football"
          },
          {
            name: "league",
            placeholder: "NFL"
          },
          {
            name: "team",
            placeholder: "Chiefs"
          },
          {
            name: "stat_type",
            placeholder: "passing_yards"
          }
        ],
        task: null,
        api_link: (...args: string[]) => `https://api.sportsdata.io/v3/nfl/stats/json/PlayerGameStatsByDate/${args[0]}/${args[1]}`,
        market_keyword: (...args: string[]) => `sport: ${args[0]}, league: ${args[1]}, team: ${args[2]}, stat: ${args[3]}`,
      },
      {
        api_name: "MLB",
        needed_data: [
          {
            name: "sport",
            placeholder: "baseball"
          },
          {
            name: "league",
            placeholder: "MLB"
          },
          {
            name: "team",
            placeholder: "Yankees"
          },
          {
            name: "stat_type",
            placeholder: "hits"
          }
        ],
        task: null,
        api_link: (...args: string[]) => `https://api.sportsdata.io/v3/mlb/stats/json/PlayerGameStatsByDate/${args[0]}/${args[1]}`,
        market_keyword: (...args: string[]) => `sport: ${args[0]}, league: ${args[1]}, team: ${args[2]}, stat: ${args[3]}`,
      },
      {
        api_name: "Soccer",
        needed_data: [
          {
            name: "sport",
            placeholder: "soccer"
          },
          {
            name: "league",
            placeholder: "Premier League"
          },
          {
            name: "team",
            placeholder: "Manchester United"
          },
          {
            name: "stat_type",
            placeholder: "goals"
          }
        ],
        task: null,
        api_link: (...args: string[]) => `https://api.sportsdata.io/v3/soccer/stats/json/PlayerGameStatsByDate/${args[0]}/${args[1]}`,
        market_keyword: (...args: string[]) => `sport: ${args[0]}, league: ${args[1]}, team: ${args[2]}, stat: ${args[3]}`,
      }
    ]
  }
]
